apply_preset:
  description: Apply a scene preset to specified light entities
  fields:
    preset_id:
      name: "Preset"
      example: "Rest"
      required: true
      selector:
        text: null
    targets:
      name: "Targets"
      required: true
      selector:
        target:
          entity:
            domain:
              - light
              - group
    brightness:
      name: "Brightness"
      example: 150
      selector:
        number:
          min: 0
          max: 255
    transition:
      name: "Transition"
      example: 1
      selector:
        number:
          min: 0
          max: 300
          unit_of_measurement: seconds
    shuffle:
      name: "Shuffle"
      example: true
      selector:
        boolean: